"""Add overall_discount_amount to billing

Revision ID: 2f3aabe3c954
Revises: 
Create Date: 2026-10-09 12:21:16.540331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f3aabe3c954'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overall_discount_amount', sa.Integer(), sa.Computed('billing_amount - applies_discount_amount', ), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing', schema=None) as batch_op:
        batch_op.drop_column('overall_discount_amount')

    # ### end Alembic commands ###
